obstacles:
  - marker_id: "300"
    name: 'obstacle_0'
    shape: rectangle
    length: 0.4
    width: 0.4
  - marker_id: "301"
    name: 'obstacle_1'
    shape: rectangle
    length: 0.4
    width: 0.4
